/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CheckTransactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckTransactionRequest{}

// CheckTransactionRequest struct for CheckTransactionRequest
type CheckTransactionRequest struct {
	Id string `form:"id" json:"id"`
}

type _CheckTransactionRequest CheckTransactionRequest

// NewCheckTransactionRequest instantiates a new CheckTransactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckTransactionRequest(id string) *CheckTransactionRequest {
	this := CheckTransactionRequest{}
	this.Id = id
	return &this
}

// NewCheckTransactionRequestWithDefaults instantiates a new CheckTransactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckTransactionRequestWithDefaults() *CheckTransactionRequest {
	this := CheckTransactionRequest{}
	return &this
}

// GetId returns the Id field value
func (o *CheckTransactionRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CheckTransactionRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CheckTransactionRequest) SetId(v string) {
	o.Id = v
}

func (o CheckTransactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckTransactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CheckTransactionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckTransactionRequest := _CheckTransactionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckTransactionRequest)

	if err != nil {
		return err
	}

	*o = CheckTransactionRequest(varCheckTransactionRequest)

	return err
}

type NullableCheckTransactionRequest struct {
	value *CheckTransactionRequest
	isSet bool
}

func (v NullableCheckTransactionRequest) Get() *CheckTransactionRequest {
	return v.value
}

func (v *NullableCheckTransactionRequest) Set(val *CheckTransactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckTransactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckTransactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckTransactionRequest(val *CheckTransactionRequest) *NullableCheckTransactionRequest {
	return &NullableCheckTransactionRequest{value: val, isSet: true}
}

func (v NullableCheckTransactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckTransactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
