/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetStatementResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStatementResponse{}

// GetStatementResponse struct for GetStatementResponse
type GetStatementResponse struct {
	Transactions []StatementTransaction `form:"transactions" json:"transactions"`
}

type _GetStatementResponse GetStatementResponse

// NewGetStatementResponse instantiates a new GetStatementResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStatementResponse(transactions []StatementTransaction) *GetStatementResponse {
	this := GetStatementResponse{}
	this.Transactions = transactions
	return &this
}

// NewGetStatementResponseWithDefaults instantiates a new GetStatementResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStatementResponseWithDefaults() *GetStatementResponse {
	this := GetStatementResponse{}
	return &this
}

// GetTransactions returns the Transactions field value
func (o *GetStatementResponse) GetTransactions() []StatementTransaction {
	if o == nil {
		var ret []StatementTransaction
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *GetStatementResponse) GetTransactionsOk() ([]StatementTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *GetStatementResponse) SetTransactions(v []StatementTransaction) {
	o.Transactions = v
}

func (o GetStatementResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStatementResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transactions"] = o.Transactions
	return toSerialize, nil
}

func (o *GetStatementResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transactions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetStatementResponse := _GetStatementResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetStatementResponse)

	if err != nil {
		return err
	}

	*o = GetStatementResponse(varGetStatementResponse)

	return err
}

type NullableGetStatementResponse struct {
	value *GetStatementResponse
	isSet bool
}

func (v NullableGetStatementResponse) Get() *GetStatementResponse {
	return v.value
}

func (v *NullableGetStatementResponse) Set(val *GetStatementResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStatementResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStatementResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStatementResponse(val *GetStatementResponse) *NullableGetStatementResponse {
	return &NullableGetStatementResponse{value: val, isSet: true}
}

func (v NullableGetStatementResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStatementResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


