/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PerformTransactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PerformTransactionRequest{}

// PerformTransactionRequest struct for PerformTransactionRequest
type PerformTransactionRequest struct {
	Id string `form:"id" json:"id"`
}

type _PerformTransactionRequest PerformTransactionRequest

// NewPerformTransactionRequest instantiates a new PerformTransactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPerformTransactionRequest(id string) *PerformTransactionRequest {
	this := PerformTransactionRequest{}
	this.Id = id
	return &this
}

// NewPerformTransactionRequestWithDefaults instantiates a new PerformTransactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPerformTransactionRequestWithDefaults() *PerformTransactionRequest {
	this := PerformTransactionRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PerformTransactionRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PerformTransactionRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PerformTransactionRequest) SetId(v string) {
	o.Id = v
}

func (o PerformTransactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PerformTransactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *PerformTransactionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPerformTransactionRequest := _PerformTransactionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPerformTransactionRequest)

	if err != nil {
		return err
	}

	*o = PerformTransactionRequest(varPerformTransactionRequest)

	return err
}

type NullablePerformTransactionRequest struct {
	value *PerformTransactionRequest
	isSet bool
}

func (v NullablePerformTransactionRequest) Get() *PerformTransactionRequest {
	return v.value
}

func (v *NullablePerformTransactionRequest) Set(val *PerformTransactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePerformTransactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePerformTransactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePerformTransactionRequest(val *PerformTransactionRequest) *NullablePerformTransactionRequest {
	return &NullablePerformTransactionRequest{value: val, isSet: true}
}

func (v NullablePerformTransactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePerformTransactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


