/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CancelTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelTransactionResponse{}

// CancelTransactionResponse struct for CancelTransactionResponse
type CancelTransactionResponse struct {
	Transaction string `form:"transaction" json:"transaction"`
	CancelTime  int64  `form:"cancel_time" json:"cancel_time"`
	State       int32  `form:"state" json:"state"`
}

type _CancelTransactionResponse CancelTransactionResponse

// NewCancelTransactionResponse instantiates a new CancelTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelTransactionResponse(transaction string, cancelTime int64, state int32) *CancelTransactionResponse {
	this := CancelTransactionResponse{}
	this.Transaction = transaction
	this.CancelTime = cancelTime
	this.State = state
	return &this
}

// NewCancelTransactionResponseWithDefaults instantiates a new CancelTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelTransactionResponseWithDefaults() *CancelTransactionResponse {
	this := CancelTransactionResponse{}
	return &this
}

// GetTransaction returns the Transaction field value
func (o *CancelTransactionResponse) GetTransaction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value
// and a boolean to check if the value has been set.
func (o *CancelTransactionResponse) GetTransactionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transaction, true
}

// SetTransaction sets field value
func (o *CancelTransactionResponse) SetTransaction(v string) {
	o.Transaction = v
}

// GetCancelTime returns the CancelTime field value
func (o *CancelTransactionResponse) GetCancelTime() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CancelTime
}

// GetCancelTimeOk returns a tuple with the CancelTime field value
// and a boolean to check if the value has been set.
func (o *CancelTransactionResponse) GetCancelTimeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CancelTime, true
}

// SetCancelTime sets field value
func (o *CancelTransactionResponse) SetCancelTime(v int64) {
	o.CancelTime = v
}

// GetState returns the State field value
func (o *CancelTransactionResponse) GetState() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *CancelTransactionResponse) GetStateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *CancelTransactionResponse) SetState(v int32) {
	o.State = v
}

func (o CancelTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transaction"] = o.Transaction
	toSerialize["cancel_time"] = o.CancelTime
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *CancelTransactionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transaction",
		"cancel_time",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelTransactionResponse := _CancelTransactionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelTransactionResponse)

	if err != nil {
		return err
	}

	*o = CancelTransactionResponse(varCancelTransactionResponse)

	return err
}

type NullableCancelTransactionResponse struct {
	value *CancelTransactionResponse
	isSet bool
}

func (v NullableCancelTransactionResponse) Get() *CancelTransactionResponse {
	return v.value
}

func (v *NullableCancelTransactionResponse) Set(val *CancelTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelTransactionResponse(val *CancelTransactionResponse) *NullableCancelTransactionResponse {
	return &NullableCancelTransactionResponse{value: val, isSet: true}
}

func (v NullableCancelTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
