/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetFiscalDataErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetFiscalDataErrorResponse{}

// SetFiscalDataErrorResponse struct for SetFiscalDataErrorResponse
type SetFiscalDataErrorResponse struct {
	Error SetFiscalDataErrorResponseError `form:"error" json:"error"`
}

type _SetFiscalDataErrorResponse SetFiscalDataErrorResponse

// NewSetFiscalDataErrorResponse instantiates a new SetFiscalDataErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetFiscalDataErrorResponse(error_ SetFiscalDataErrorResponseError) *SetFiscalDataErrorResponse {
	this := SetFiscalDataErrorResponse{}
	this.Error = error_
	return &this
}

// NewSetFiscalDataErrorResponseWithDefaults instantiates a new SetFiscalDataErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetFiscalDataErrorResponseWithDefaults() *SetFiscalDataErrorResponse {
	this := SetFiscalDataErrorResponse{}
	return &this
}

// GetError returns the Error field value
func (o *SetFiscalDataErrorResponse) GetError() SetFiscalDataErrorResponseError {
	if o == nil {
		var ret SetFiscalDataErrorResponseError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *SetFiscalDataErrorResponse) GetErrorOk() (*SetFiscalDataErrorResponseError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *SetFiscalDataErrorResponse) SetError(v SetFiscalDataErrorResponseError) {
	o.Error = v
}

func (o SetFiscalDataErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetFiscalDataErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *SetFiscalDataErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetFiscalDataErrorResponse := _SetFiscalDataErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetFiscalDataErrorResponse)

	if err != nil {
		return err
	}

	*o = SetFiscalDataErrorResponse(varSetFiscalDataErrorResponse)

	return err
}

type NullableSetFiscalDataErrorResponse struct {
	value *SetFiscalDataErrorResponse
	isSet bool
}

func (v NullableSetFiscalDataErrorResponse) Get() *SetFiscalDataErrorResponse {
	return v.value
}

func (v *NullableSetFiscalDataErrorResponse) Set(val *SetFiscalDataErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSetFiscalDataErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSetFiscalDataErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetFiscalDataErrorResponse(val *SetFiscalDataErrorResponse) *NullableSetFiscalDataErrorResponse {
	return &NullableSetFiscalDataErrorResponse{value: val, isSet: true}
}

func (v NullableSetFiscalDataErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetFiscalDataErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


