/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Receiver type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Receiver{}

// Receiver struct for Receiver
type Receiver struct {
	Id string `form:"id" json:"id"`
	Amount int32 `form:"amount" json:"amount"`
}

type _Receiver Receiver

// NewReceiver instantiates a new Receiver object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceiver(id string, amount int32) *Receiver {
	this := Receiver{}
	this.Id = id
	this.Amount = amount
	return &this
}

// NewReceiverWithDefaults instantiates a new Receiver object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiverWithDefaults() *Receiver {
	this := Receiver{}
	return &this
}

// GetId returns the Id field value
func (o *Receiver) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Receiver) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Receiver) SetId(v string) {
	o.Id = v
}

// GetAmount returns the Amount field value
func (o *Receiver) GetAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *Receiver) GetAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *Receiver) SetAmount(v int32) {
	o.Amount = v
}

func (o Receiver) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Receiver) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *Receiver) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceiver := _Receiver{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReceiver)

	if err != nil {
		return err
	}

	*o = Receiver(varReceiver)

	return err
}

type NullableReceiver struct {
	value *Receiver
	isSet bool
}

func (v NullableReceiver) Get() *Receiver {
	return v.value
}

func (v *NullableReceiver) Set(val *Receiver) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiver) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiver) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiver(val *Receiver) *NullableReceiver {
	return &NullableReceiver{value: val, isSet: true}
}

func (v NullableReceiver) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiver) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


