/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetFiscalDataErrorResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetFiscalDataErrorResponseError{}

// SetFiscalDataErrorResponseError struct for SetFiscalDataErrorResponseError
type SetFiscalDataErrorResponseError struct {
	Code int32 `form:"code" json:"code"`
	Message string `form:"message" json:"message"`
}

type _SetFiscalDataErrorResponseError SetFiscalDataErrorResponseError

// NewSetFiscalDataErrorResponseError instantiates a new SetFiscalDataErrorResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetFiscalDataErrorResponseError(code int32, message string) *SetFiscalDataErrorResponseError {
	this := SetFiscalDataErrorResponseError{}
	this.Code = code
	this.Message = message
	return &this
}

// NewSetFiscalDataErrorResponseErrorWithDefaults instantiates a new SetFiscalDataErrorResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetFiscalDataErrorResponseErrorWithDefaults() *SetFiscalDataErrorResponseError {
	this := SetFiscalDataErrorResponseError{}
	return &this
}

// GetCode returns the Code field value
func (o *SetFiscalDataErrorResponseError) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *SetFiscalDataErrorResponseError) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *SetFiscalDataErrorResponseError) SetCode(v int32) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *SetFiscalDataErrorResponseError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SetFiscalDataErrorResponseError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SetFiscalDataErrorResponseError) SetMessage(v string) {
	o.Message = v
}

func (o SetFiscalDataErrorResponseError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetFiscalDataErrorResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *SetFiscalDataErrorResponseError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetFiscalDataErrorResponseError := _SetFiscalDataErrorResponseError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetFiscalDataErrorResponseError)

	if err != nil {
		return err
	}

	*o = SetFiscalDataErrorResponseError(varSetFiscalDataErrorResponseError)

	return err
}

type NullableSetFiscalDataErrorResponseError struct {
	value *SetFiscalDataErrorResponseError
	isSet bool
}

func (v NullableSetFiscalDataErrorResponseError) Get() *SetFiscalDataErrorResponseError {
	return v.value
}

func (v *NullableSetFiscalDataErrorResponseError) Set(val *SetFiscalDataErrorResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableSetFiscalDataErrorResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableSetFiscalDataErrorResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetFiscalDataErrorResponseError(val *SetFiscalDataErrorResponseError) *NullableSetFiscalDataErrorResponseError {
	return &NullableSetFiscalDataErrorResponseError{value: val, isSet: true}
}

func (v NullableSetFiscalDataErrorResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetFiscalDataErrorResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


