/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CheckPerformTransactionRequestWrapper type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckPerformTransactionRequestWrapper{}

// CheckPerformTransactionRequestWrapper struct for CheckPerformTransactionRequestWrapper
type CheckPerformTransactionRequestWrapper struct {
	Jsonrpc string                         `form:"jsonrpc" json:"jsonrpc"`
	Id      int64                          `form:"id" json:"id"`
	Method  string                         `form:"method" json:"method"`
	Params  CheckPerformTransactionRequest `form:"params" json:"params"`
}

type _CheckPerformTransactionRequestWrapper CheckPerformTransactionRequestWrapper

// NewCheckPerformTransactionRequestWrapper instantiates a new CheckPerformTransactionRequestWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckPerformTransactionRequestWrapper(jsonrpc string, id int64, method string, params CheckPerformTransactionRequest) *CheckPerformTransactionRequestWrapper {
	this := CheckPerformTransactionRequestWrapper{}
	this.Jsonrpc = jsonrpc
	this.Id = id
	this.Method = method
	this.Params = params
	return &this
}

// NewCheckPerformTransactionRequestWrapperWithDefaults instantiates a new CheckPerformTransactionRequestWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckPerformTransactionRequestWrapperWithDefaults() *CheckPerformTransactionRequestWrapper {
	this := CheckPerformTransactionRequestWrapper{}
	return &this
}

// GetJsonrpc returns the Jsonrpc field value
func (o *CheckPerformTransactionRequestWrapper) GetJsonrpc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Jsonrpc
}

// GetJsonrpcOk returns a tuple with the Jsonrpc field value
// and a boolean to check if the value has been set.
func (o *CheckPerformTransactionRequestWrapper) GetJsonrpcOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonrpc, true
}

// SetJsonrpc sets field value
func (o *CheckPerformTransactionRequestWrapper) SetJsonrpc(v string) {
	o.Jsonrpc = v
}

// GetId returns the Id field value
func (o *CheckPerformTransactionRequestWrapper) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CheckPerformTransactionRequestWrapper) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CheckPerformTransactionRequestWrapper) SetId(v int64) {
	o.Id = v
}

// GetMethod returns the Method field value
func (o *CheckPerformTransactionRequestWrapper) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *CheckPerformTransactionRequestWrapper) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *CheckPerformTransactionRequestWrapper) SetMethod(v string) {
	o.Method = v
}

// GetParams returns the Params field value
func (o *CheckPerformTransactionRequestWrapper) GetParams() CheckPerformTransactionRequest {
	if o == nil {
		var ret CheckPerformTransactionRequest
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *CheckPerformTransactionRequestWrapper) GetParamsOk() (*CheckPerformTransactionRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *CheckPerformTransactionRequestWrapper) SetParams(v CheckPerformTransactionRequest) {
	o.Params = v
}

func (o CheckPerformTransactionRequestWrapper) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckPerformTransactionRequestWrapper) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jsonrpc"] = o.Jsonrpc
	toSerialize["id"] = o.Id
	toSerialize["method"] = o.Method
	toSerialize["params"] = o.Params
	return toSerialize, nil
}

func (o *CheckPerformTransactionRequestWrapper) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jsonrpc",
		"id",
		"method",
		"params",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckPerformTransactionRequestWrapper := _CheckPerformTransactionRequestWrapper{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckPerformTransactionRequestWrapper)

	if err != nil {
		return err
	}

	*o = CheckPerformTransactionRequestWrapper(varCheckPerformTransactionRequestWrapper)

	return err
}

type NullableCheckPerformTransactionRequestWrapper struct {
	value *CheckPerformTransactionRequestWrapper
	isSet bool
}

func (v NullableCheckPerformTransactionRequestWrapper) Get() *CheckPerformTransactionRequestWrapper {
	return v.value
}

func (v *NullableCheckPerformTransactionRequestWrapper) Set(val *CheckPerformTransactionRequestWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckPerformTransactionRequestWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckPerformTransactionRequestWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckPerformTransactionRequestWrapper(val *CheckPerformTransactionRequestWrapper) *NullableCheckPerformTransactionRequestWrapper {
	return &NullableCheckPerformTransactionRequestWrapper{value: val, isSet: true}
}

func (v NullableCheckPerformTransactionRequestWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckPerformTransactionRequestWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
