/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckPerformTransactionRequestAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckPerformTransactionRequestAccount{}

// CheckPerformTransactionRequestAccount struct for CheckPerformTransactionRequestAccount
type CheckPerformTransactionRequestAccount struct {
	Phone string `form:"phone" json:"phone"`
}

type _CheckPerformTransactionRequestAccount CheckPerformTransactionRequestAccount

// NewCheckPerformTransactionRequestAccount instantiates a new CheckPerformTransactionRequestAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckPerformTransactionRequestAccount(phone string) *CheckPerformTransactionRequestAccount {
	this := CheckPerformTransactionRequestAccount{}
	this.Phone = phone
	return &this
}

// NewCheckPerformTransactionRequestAccountWithDefaults instantiates a new CheckPerformTransactionRequestAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckPerformTransactionRequestAccountWithDefaults() *CheckPerformTransactionRequestAccount {
	this := CheckPerformTransactionRequestAccount{}
	return &this
}

// GetPhone returns the Phone field value
func (o *CheckPerformTransactionRequestAccount) GetPhone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *CheckPerformTransactionRequestAccount) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *CheckPerformTransactionRequestAccount) SetPhone(v string) {
	o.Phone = v
}

func (o CheckPerformTransactionRequestAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckPerformTransactionRequestAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone"] = o.Phone
	return toSerialize, nil
}

func (o *CheckPerformTransactionRequestAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckPerformTransactionRequestAccount := _CheckPerformTransactionRequestAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckPerformTransactionRequestAccount)

	if err != nil {
		return err
	}

	*o = CheckPerformTransactionRequestAccount(varCheckPerformTransactionRequestAccount)

	return err
}

type NullableCheckPerformTransactionRequestAccount struct {
	value *CheckPerformTransactionRequestAccount
	isSet bool
}

func (v NullableCheckPerformTransactionRequestAccount) Get() *CheckPerformTransactionRequestAccount {
	return v.value
}

func (v *NullableCheckPerformTransactionRequestAccount) Set(val *CheckPerformTransactionRequestAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckPerformTransactionRequestAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckPerformTransactionRequestAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckPerformTransactionRequestAccount(val *CheckPerformTransactionRequestAccount) *NullableCheckPerformTransactionRequestAccount {
	return &NullableCheckPerformTransactionRequestAccount{value: val, isSet: true}
}

func (v NullableCheckPerformTransactionRequestAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckPerformTransactionRequestAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


