/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the JSONRPCErrorResponseError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JSONRPCErrorResponseError{}

// JSONRPCErrorResponseError struct for JSONRPCErrorResponseError
type JSONRPCErrorResponseError struct {
	Code    int32                            `form:"code" json:"code"`
	Message JSONRPCErrorResponseErrorMessage `form:"message" json:"message"`
	Data    *string                          `form:"data" json:"data,omitempty"`
}

type _JSONRPCErrorResponseError JSONRPCErrorResponseError

// NewJSONRPCErrorResponseError instantiates a new JSONRPCErrorResponseError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJSONRPCErrorResponseError(code int32, message JSONRPCErrorResponseErrorMessage) *JSONRPCErrorResponseError {
	this := JSONRPCErrorResponseError{}
	this.Code = code
	this.Message = message
	return &this
}

// NewJSONRPCErrorResponseErrorWithDefaults instantiates a new JSONRPCErrorResponseError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJSONRPCErrorResponseErrorWithDefaults() *JSONRPCErrorResponseError {
	this := JSONRPCErrorResponseError{}
	return &this
}

// GetCode returns the Code field value
func (o *JSONRPCErrorResponseError) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *JSONRPCErrorResponseError) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *JSONRPCErrorResponseError) SetCode(v int32) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *JSONRPCErrorResponseError) GetMessage() JSONRPCErrorResponseErrorMessage {
	if o == nil {
		var ret JSONRPCErrorResponseErrorMessage
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *JSONRPCErrorResponseError) GetMessageOk() (*JSONRPCErrorResponseErrorMessage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *JSONRPCErrorResponseError) SetMessage(v JSONRPCErrorResponseErrorMessage) {
	o.Message = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *JSONRPCErrorResponseError) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JSONRPCErrorResponseError) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *JSONRPCErrorResponseError) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *JSONRPCErrorResponseError) SetData(v string) {
	o.Data = &v
}

func (o JSONRPCErrorResponseError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JSONRPCErrorResponseError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

func (o *JSONRPCErrorResponseError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJSONRPCErrorResponseError := _JSONRPCErrorResponseError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJSONRPCErrorResponseError)

	if err != nil {
		return err
	}

	*o = JSONRPCErrorResponseError(varJSONRPCErrorResponseError)

	return err
}

type NullableJSONRPCErrorResponseError struct {
	value *JSONRPCErrorResponseError
	isSet bool
}

func (v NullableJSONRPCErrorResponseError) Get() *JSONRPCErrorResponseError {
	return v.value
}

func (v *NullableJSONRPCErrorResponseError) Set(val *JSONRPCErrorResponseError) {
	v.value = val
	v.isSet = true
}

func (v NullableJSONRPCErrorResponseError) IsSet() bool {
	return v.isSet
}

func (v *NullableJSONRPCErrorResponseError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJSONRPCErrorResponseError(val *JSONRPCErrorResponseError) *NullableJSONRPCErrorResponseError {
	return &NullableJSONRPCErrorResponseError{value: val, isSet: true}
}

func (v NullableJSONRPCErrorResponseError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJSONRPCErrorResponseError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
