/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JSONRPCErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JSONRPCErrorResponse{}

// JSONRPCErrorResponse struct for JSONRPCErrorResponse
type JSONRPCErrorResponse struct {
	Error JSONRPCErrorResponseError `form:"error" json:"error"`
	Id int64 `form:"id" json:"id"`
}

type _JSONRPCErrorResponse JSONRPCErrorResponse

// NewJSONRPCErrorResponse instantiates a new JSONRPCErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJSONRPCErrorResponse(error_ JSONRPCErrorResponseError, id int64) *JSONRPCErrorResponse {
	this := JSONRPCErrorResponse{}
	this.Error = error_
	this.Id = id
	return &this
}

// NewJSONRPCErrorResponseWithDefaults instantiates a new JSONRPCErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJSONRPCErrorResponseWithDefaults() *JSONRPCErrorResponse {
	this := JSONRPCErrorResponse{}
	return &this
}

// GetError returns the Error field value
func (o *JSONRPCErrorResponse) GetError() JSONRPCErrorResponseError {
	if o == nil {
		var ret JSONRPCErrorResponseError
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *JSONRPCErrorResponse) GetErrorOk() (*JSONRPCErrorResponseError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *JSONRPCErrorResponse) SetError(v JSONRPCErrorResponseError) {
	o.Error = v
}

// GetId returns the Id field value
func (o *JSONRPCErrorResponse) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JSONRPCErrorResponse) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JSONRPCErrorResponse) SetId(v int64) {
	o.Id = v
}

func (o JSONRPCErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JSONRPCErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *JSONRPCErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJSONRPCErrorResponse := _JSONRPCErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJSONRPCErrorResponse)

	if err != nil {
		return err
	}

	*o = JSONRPCErrorResponse(varJSONRPCErrorResponse)

	return err
}

type NullableJSONRPCErrorResponse struct {
	value *JSONRPCErrorResponse
	isSet bool
}

func (v NullableJSONRPCErrorResponse) Get() *JSONRPCErrorResponse {
	return v.value
}

func (v *NullableJSONRPCErrorResponse) Set(val *JSONRPCErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJSONRPCErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJSONRPCErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJSONRPCErrorResponse(val *JSONRPCErrorResponse) *NullableJSONRPCErrorResponse {
	return &NullableJSONRPCErrorResponse{value: val, isSet: true}
}

func (v NullableJSONRPCErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJSONRPCErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


