/*
Payme Merchant API

API for managing Payme Merchant.

API version: 1.0.0
Contact: danil@iota.uz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymeapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CancelTransactionRequestWrapper type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelTransactionRequestWrapper{}

// CancelTransactionRequestWrapper struct for CancelTransactionRequestWrapper
type CancelTransactionRequestWrapper struct {
	Jsonrpc string                   `form:"jsonrpc" json:"jsonrpc"`
	Id      int64                    `form:"id" json:"id"`
	Method  string                   `form:"method" json:"method"`
	Params  CancelTransactionRequest `form:"params" json:"params"`
}

type _CancelTransactionRequestWrapper CancelTransactionRequestWrapper

// NewCancelTransactionRequestWrapper instantiates a new CancelTransactionRequestWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelTransactionRequestWrapper(jsonrpc string, id int64, method string, params CancelTransactionRequest) *CancelTransactionRequestWrapper {
	this := CancelTransactionRequestWrapper{}
	this.Jsonrpc = jsonrpc
	this.Id = id
	this.Method = method
	this.Params = params
	return &this
}

// NewCancelTransactionRequestWrapperWithDefaults instantiates a new CancelTransactionRequestWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelTransactionRequestWrapperWithDefaults() *CancelTransactionRequestWrapper {
	this := CancelTransactionRequestWrapper{}
	return &this
}

// GetJsonrpc returns the Jsonrpc field value
func (o *CancelTransactionRequestWrapper) GetJsonrpc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Jsonrpc
}

// GetJsonrpcOk returns a tuple with the Jsonrpc field value
// and a boolean to check if the value has been set.
func (o *CancelTransactionRequestWrapper) GetJsonrpcOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Jsonrpc, true
}

// SetJsonrpc sets field value
func (o *CancelTransactionRequestWrapper) SetJsonrpc(v string) {
	o.Jsonrpc = v
}

// GetId returns the Id field value
func (o *CancelTransactionRequestWrapper) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CancelTransactionRequestWrapper) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CancelTransactionRequestWrapper) SetId(v int64) {
	o.Id = v
}

// GetMethod returns the Method field value
func (o *CancelTransactionRequestWrapper) GetMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Method
}

// GetMethodOk returns a tuple with the Method field value
// and a boolean to check if the value has been set.
func (o *CancelTransactionRequestWrapper) GetMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Method, true
}

// SetMethod sets field value
func (o *CancelTransactionRequestWrapper) SetMethod(v string) {
	o.Method = v
}

// GetParams returns the Params field value
func (o *CancelTransactionRequestWrapper) GetParams() CancelTransactionRequest {
	if o == nil {
		var ret CancelTransactionRequest
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *CancelTransactionRequestWrapper) GetParamsOk() (*CancelTransactionRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *CancelTransactionRequestWrapper) SetParams(v CancelTransactionRequest) {
	o.Params = v
}

func (o CancelTransactionRequestWrapper) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelTransactionRequestWrapper) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jsonrpc"] = o.Jsonrpc
	toSerialize["id"] = o.Id
	toSerialize["method"] = o.Method
	toSerialize["params"] = o.Params
	return toSerialize, nil
}

func (o *CancelTransactionRequestWrapper) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jsonrpc",
		"id",
		"method",
		"params",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelTransactionRequestWrapper := _CancelTransactionRequestWrapper{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelTransactionRequestWrapper)

	if err != nil {
		return err
	}

	*o = CancelTransactionRequestWrapper(varCancelTransactionRequestWrapper)

	return err
}

type NullableCancelTransactionRequestWrapper struct {
	value *CancelTransactionRequestWrapper
	isSet bool
}

func (v NullableCancelTransactionRequestWrapper) Get() *CancelTransactionRequestWrapper {
	return v.value
}

func (v *NullableCancelTransactionRequestWrapper) Set(val *CancelTransactionRequestWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelTransactionRequestWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelTransactionRequestWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelTransactionRequestWrapper(val *CancelTransactionRequestWrapper) *NullableCancelTransactionRequestWrapper {
	return &NullableCancelTransactionRequestWrapper{value: val, isSet: true}
}

func (v NullableCancelTransactionRequestWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelTransactionRequestWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
